# Auto-generated by prompts/test-generator.yaml
# Maps every Gherkin scenario in specs/url-shortener.yaml to at least one test.
# Uses an in-memory SQLite DB — no real network calls.

import pytest
from datetime import datetime, timezone, timedelta
from src import create_app
from src.extensions import db as _db


# ─────────────────────────────────────────────────────────────────────────────
# FIXTURES
# ─────────────────────────────────────────────────────────────────────────────

@pytest.fixture
def app():
    """Create a fresh Flask app with in-memory SQLite for every test session."""
    test_config = {
        "TESTING": True,
        "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
        "BASE_URL": "http://localhost",
        "BLOCKED_DOMAINS": ["malware.example.com", "phishing.example.org"],
        "RATELIMIT_ENABLED": False,   # disable rate limiting in tests
    }
    application = create_app(test_config)
    with application.app_context():
        _db.create_all()
        yield application
        _db.session.remove()
        _db.drop_all()


@pytest.fixture
def client(app):
    return app.test_client()


def _shorten(client, url, **kwargs):
    """Helper: POST /api/shorten with a JSON body."""
    body = {"url": url, **kwargs}
    return client.post("/api/shorten", json=body)


# ─────────────────────────────────────────────────────────────────────────────
# PART 1 — CORE SHORTENING
# ─────────────────────────────────────────────────────────────────────────────

class TestShortenURL:

    # Tests: REQ-SHORT-001 | SCENARIO-001
    def test_should_return_201_when_valid_url_submitted(self, client):
        resp = _shorten(client, "https://www.example.com/some/long/path")
        assert resp.status_code == 201
        body = resp.get_json()
        assert body["success"] is True
        assert len(body["data"]["short_code"]) == 6
        assert body["data"]["original_url"] == "https://www.example.com/some/long/path"

    # Tests: REQ-SHORT-001 | SCENARIO-001
    def test_should_contain_short_url_in_response(self, client):
        resp = _shorten(client, "https://example.com")
        data = resp.get_json()["data"]
        assert data["short_url"].startswith("http://localhost/")

    # Tests: REQ-SHORT-003 | SCENARIO-007
    def test_should_use_custom_alias_when_provided(self, client):
        resp = _shorten(client, "https://example.com/page", custom_alias="myalias")
        assert resp.status_code == 201
        assert resp.get_json()["data"]["short_code"] == "myalias"

    # Tests: REQ-EXP-001 | SCENARIO-010
    def test_should_store_expiry_date_when_expires_at_provided(self, client):
        future = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        resp = _shorten(client, "https://example.com/expiring", expires_at=future)
        assert resp.status_code == 201
        assert resp.get_json()["data"]["expires_at"] is not None

    # Tests: REQ-API-001
    def test_should_return_error_envelope_when_url_missing(self, client):
        resp = client.post("/api/shorten", json={})
        assert resp.status_code == 422
        body = resp.get_json()
        assert body["success"] is False
        assert body["error"] is not None


# ─────────────────────────────────────────────────────────────────────────────
# PART 2 — VALIDATION
# ─────────────────────────────────────────────────────────────────────────────

class TestValidation:

    # Tests: REQ-VAL-001 | SCENARIO-005
    def test_should_return_422_when_url_has_ftp_scheme(self, client):
        resp = _shorten(client, "ftp://files.example.com")
        assert resp.status_code == 422
        assert "http" in resp.get_json()["error"].lower()

    # Tests: REQ-VAL-001
    def test_should_return_422_when_url_has_no_scheme(self, client):
        resp = _shorten(client, "www.example.com")
        assert resp.status_code == 422

    # Tests: REQ-VAL-002 | SCENARIO-006
    def test_should_return_409_when_url_already_shortened(self, client):
        _shorten(client, "https://www.example.com/page")
        resp = _shorten(client, "https://www.example.com/page")
        assert resp.status_code == 409

    # Tests: REQ-VAL-003
    def test_should_return_422_when_domain_is_blocked(self, client):
        resp = _shorten(client, "https://malware.example.com/bad")
        assert resp.status_code == 422
        assert resp.get_json()["error"] is not None

    # Tests: REQ-VAL-004 | SCENARIO-008
    def test_should_return_409_when_custom_alias_already_taken(self, client):
        _shorten(client, "https://example.com/first", custom_alias="taken")
        resp = _shorten(client, "https://example.com/second", custom_alias="taken")
        assert resp.status_code == 409
        assert "taken" in resp.get_json()["error"].lower()

    # Tests: REQ-VAL-004 (alias format)
    @pytest.mark.parametrize("bad_alias", ["ab", "this-alias-is-way-too-long-for-the-system", "has space", "has@symbol"])
    def test_should_return_422_when_alias_format_is_invalid(self, client, bad_alias):
        resp = _shorten(client, "https://example.com", custom_alias=bad_alias)
        assert resp.status_code == 422


# ─────────────────────────────────────────────────────────────────────────────
# PART 3 — REDIRECT
# ─────────────────────────────────────────────────────────────────────────────

class TestRedirect:

    # Tests: REQ-REDIR-001 | SCENARIO-002
    def test_should_redirect_302_when_valid_code_requested(self, client):
        create_resp = _shorten(client, "https://www.example.com")
        code = create_resp.get_json()["data"]["short_code"]
        resp = client.get(f"/{code}")
        assert resp.status_code == 302
        assert resp.headers["Location"] == "https://www.example.com"

    # Tests: REQ-REDIR-002 | SCENARIO-003
    def test_should_return_404_when_code_does_not_exist(self, client):
        resp = client.get("/xxxxxx")
        assert resp.status_code == 404
        body = resp.get_json()
        assert body["success"] is False
        assert "not found" in body["error"].lower()

    # Tests: REQ-REDIR-003, REQ-EXP-002 | SCENARIO-004
    def test_should_return_410_when_url_is_expired(self, client):
        past = (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
        create_resp = _shorten(client, "https://example.com/old", expires_at=past)
        code = create_resp.get_json()["data"]["short_code"]
        resp = client.get(f"/{code}")
        assert resp.status_code == 410
        assert "expired" in resp.get_json()["error"].lower()

    # Tests: REQ-REDIR-001 (future expiry should still redirect)
    def test_should_redirect_when_expiry_is_in_future(self, client):
        future = (datetime.now(timezone.utc) + timedelta(days=1)).isoformat()
        create_resp = _shorten(client, "https://example.com/future", expires_at=future)
        code = create_resp.get_json()["data"]["short_code"]
        resp = client.get(f"/{code}")
        assert resp.status_code == 302


# ─────────────────────────────────────────────────────────────────────────────
# PART 4 — ANALYTICS
# ─────────────────────────────────────────────────────────────────────────────

class TestAnalytics:

    # Tests: REQ-ANAL-001, REQ-ANAL-002 | SCENARIO-002
    def test_should_increment_click_count_on_redirect(self, client):
        code = _shorten(client, "https://analytics.example.com").get_json()["data"]["short_code"]
        client.get(f"/{code}")
        client.get(f"/{code}")
        client.get(f"/{code}")
        stats = client.get(f"/api/urls/{code}/stats").get_json()["data"]
        assert stats["click_count"] == 3

    # Tests: REQ-ANAL-002
    def test_should_update_last_accessed_after_redirect(self, client):
        code = _shorten(client, "https://time.example.com").get_json()["data"]["short_code"]
        assert client.get(f"/api/urls/{code}/stats").get_json()["data"]["last_accessed"] is None
        client.get(f"/{code}")
        last_accessed = client.get(f"/api/urls/{code}/stats").get_json()["data"]["last_accessed"]
        assert last_accessed is not None

    # Tests: REQ-ANAL-003
    def test_should_capture_referrer_header_on_redirect(self, client):
        code = _shorten(client, "https://ref.example.com").get_json()["data"]["short_code"]
        client.get(f"/{code}", headers={"Referer": "https://google.com"})
        stats = client.get(f"/api/urls/{code}/stats").get_json()["data"]
        assert stats["referrer"] == "https://google.com"

    # Tests: REQ-ANAL-004 | SCENARIO-009
    def test_should_return_stats_with_all_fields(self, client):
        code = _shorten(client, "https://full.example.com").get_json()["data"]["short_code"]
        resp = client.get(f"/api/urls/{code}/stats")
        assert resp.status_code == 200
        data = resp.get_json()["data"]
        for field in ["short_code", "original_url", "click_count", "last_accessed", "referrer", "created_at", "expires_at"]:
            assert field in data

    # Tests: REQ-ANAL-004
    def test_should_return_404_stats_when_code_not_found(self, client):
        resp = client.get("/api/urls/noexist/stats")
        assert resp.status_code == 404


# ─────────────────────────────────────────────────────────────────────────────
# PART 5 — EDGE CASES
# ─────────────────────────────────────────────────────────────────────────────

class TestEdgeCases:

    # Tests: REQ-SHORT-001 (no expiry = never expires)
    def test_should_redirect_forever_when_no_expiry_set(self, client):
        code = _shorten(client, "https://forever.example.com").get_json()["data"]["short_code"]
        resp = client.get(f"/{code}")
        assert resp.status_code == 302

    # Tests: REQ-API-002 (bad JSON body)
    def test_should_handle_malformed_json_gracefully(self, client):
        resp = client.post("/api/shorten", data="not-json", content_type="application/json")
        assert resp.status_code in (400, 422)

    # Tests: REQ-VAL-001 (empty string URL)
    def test_should_return_422_when_url_is_empty_string(self, client):
        resp = _shorten(client, "")
        assert resp.status_code == 422

    # Tests: REQ-SHORT-001 (http:// also valid)
    def test_should_accept_http_scheme_urls(self, client):
        resp = _shorten(client, "http://example.com/page")
        assert resp.status_code == 201

    # Tests: REQ-API-002
    def test_should_return_405_on_wrong_method(self, client):
        resp = client.get("/api/shorten")
        assert resp.status_code == 405
